### ISSUE TITLE
segfaults and no temperature on Ubuntu 14.04 after install version 331

### ISSUE THREAD

**Issue by SBFspot** [SBFspot/SBFspot#165]
Afetr seeing segfaults in older build of SBFspot, I upofraded to version 331.
Still segfaults are reported in dmesg:
[549779.761902] SBFspot[11310]: segfault at 18008082e8 ip 0000000000414eab sp 00007ffd67850ef0 error 4 in SBFspot[400000+5a000]
[550079.245144] SBFspot[11449]: segfault at 1801a812e8 ip 0000000000414eab sp 00007ffd809e9b50 error 4 in SBFspot[400000+5a000]
[550378.724190] SBFspot[11589]: segfault at 18020a42e8 ip 0000000000414eab sp 00007ffe52ce9700 error 4 in SBFspot[400000+5a000]
[550679.605312] SBFspot[11744]: segfault at 18010f02e8 ip 0000000000414eab sp 00007ffdb753a3c0 error 4 in SBFspot[400000+5a000]
[550979.037431] SBFspot[11890]: segfault at 18022162e8 ip 0000000000414eab sp 00007ffd41fd11d0 error 4 in SBFspot[400000+5a000]
[551279.857549] SBFspot[12030]: segfault at 18012e72e8 ip 0000000000414eab sp 00007ffee5585430 error 4 in SBFspot[400000+5a000]
[551579.372631] SBFspot[12167]: segfault at 18014f42e8 ip 0000000000414eab sp 00007fff73091610 error 4 in SBFspot[400000+5a000]
[551878.904650] SBFspot[12290]: segfault at 1800ab82e8 ip 0000000000414eab sp 00007ffd9c79cfb0 error 4 in SBFspot[400000+5a000]
[552178.504711] SBFspot[12420]: segfault at 18021f72e8 ip 0000000000414eab sp 00007fff3f84b950 error 4 in SBFspot[400000+5a000]
[552479.241861] SBFspot[12561]: segfault at 18022f82e8 ip 0000000000414eab sp 00007fff0139e7a0 error 4 in SBFspot[400000+5a000]
[552778.771809] SBFspot[12693]: segfault at 1801a802e8 ip 0000000000414eab sp 00007fff56ab3710 error 4 in SBFspot[400000+5a000]
[553079.530708] SBFspot[12823]: segfault at 1801ee02e8 ip 0000000000414eab sp 00007ffcbe954bb0 error 4 in SBFspot[400000+5a000]

But also temperature is not reported anymore.

Please suggest further actions to investigate.

#### Attachments
[SBFspot.out](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=SBFspot&WorkItemId=161&FileAttachmentId=1606364)
[SBFspot.core.gz](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=SBFspot&WorkItemId=161&FileAttachmentId=1606365)

#### This work item was migrated from CodePlex
CodePlex work item ID: '161'
Vote count: '1'

**Comment by SBFspot** [comment]
[SBF@12/09/2016]
Let's start with a full debug log (-d5 -v5)
I'll check my Ubuntu VM for this, but until now, I've never seen this with V3.3.1

> But also temperature is not reported anymore. 

It was visible before? What version did you run before the upgrade?

**Comment by SBFspot** [comment]
[peut@12/09/2016]
HI,

Before version 3.3.1I was running version 3.1.2. As I run SBFspot in Domoticz I can tell in the log that temperature stoppped being reported from the moment I installed version 3.3.1.

I ran SBFspot like so:

```root@ubupeut:/home/domoticz/SBFspot# spot='/usr/local/bin/sbfspot.3/SBFspot'
root@ubupeut:/home/domoticz/SBFspot# $spot -finq -d5 -v5 >SBFspot.out 2>&1
*** Error in `/usr/local/bin/sbfspot.3/SBFspot': munmap_chunk(): invalid pointer: 0x0000000000b3cde0 ***
Aborted (core dumped)

Output attached. 
Apart from the core dump there is nothing that looks strange to me. Hopefully one of you spots an issue

```

**Comment by SBFspot** [comment]
[peut@12/09/2016]
If you are interested and/or can use it, I managedto save the core dump, after some fiddling with apport and ulimit. See attached.

**Comment by SBFspot** [comment]
[SBF@20/09/2016]
I installed Ubuntu 14.04 and SBFspot on virtualbox
```
uname -a
Linux sbf-VirtualBox 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
SBFspot worke fine, nothing in dmesg (dmesg | grep SBFspot)
Using gdb, program just stops
```
sbf@sbf-VirtualBox:~/sbfspot.3/SBFspot/bin/Debug_SQLite$ gdb SBFspot coredump
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from SBFspot...done.

warning: exec file is newer than core file.
[New LWP 14570]
Core was generated by `/usr/local/bin/sbfspot.3/SBFspot -finq -d5 -v5'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f516d71fc37 in ?? ()

```

**Comment by SBFspot** [comment]
[peut@20/09/2016]
Hmm. Too bad. I tried gdb as well and found a little bit more:

```
Reading symbols from /usr/local/bin/sbfspot.3/SBFspot...(no debugging symbols found)...done.
[New LWP 14570]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/sbfspot.3/SBFspot -finq -d5 -v5'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f516d71fc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb)

```

Does your virtual machine have more than 1 CPU? My Ubuntu system has:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4

```

No clue really, but just trying.

**Comment by SBFspot** [comment]
**Issue closed by _SBF_ with comment**
Unable to reproduce the issue.

**Reason closed**
Won't Fix
